// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderService.Infrastructure.Persistence;

#nullable disable

namespace OrderService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OrderDbContext))]
    partial class OrderDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OrderService.Domain.Aggregates.OrderAggregate.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("OrderService.Domain.Aggregates.OrderAggregate.TicketReservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("TicketReservations", (string)null);
                });

            modelBuilder.Entity("OrderService.Domain.Aggregates.OrderAggregate.TrainSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StationFrom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("StationTo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TrainId")
                        .HasColumnType("int");

                    b.Property<Guid?>("TripSegmentSnapshotId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("WagonClassesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TripSegmentSnapshotId")
                        .IsUnique()
                        .HasFilter("[TripSegmentSnapshotId] IS NOT NULL");

                    b.ToTable("TrainSnapshots", (string)null);
                });

            modelBuilder.Entity("OrderService.Domain.Aggregates.OrderAggregate.TripSegmentSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("ArriveAt")
                        .HasColumnType("bigint");

                    b.Property<long>("DepartAt")
                        .HasColumnType("bigint");

                    b.Property<int>("SegmentId")
                        .HasColumnType("int");

                    b.Property<string>("StationFrom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("StationTo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("StationsTimeOffset")
                        .HasColumnType("int");

                    b.Property<Guid?>("TripSnapshotId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TripSnapshotId");

                    b.ToTable("TripSegmentSnapshots", (string)null);
                });

            modelBuilder.Entity("OrderService.Domain.Aggregates.OrderAggregate.TripSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StationFrom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("StationTo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("TicketReservationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TicketReservationId")
                        .IsUnique()
                        .HasFilter("[TicketReservationId] IS NOT NULL");

                    b.ToTable("TripSnapshots", (string)null);
                });

            modelBuilder.Entity("OrderService.Domain.Aggregates.OrderAggregate.TicketReservation", b =>
                {
                    b.HasOne("OrderService.Domain.Aggregates.OrderAggregate.Order", null)
                        .WithMany("Reservations")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("OrderService.Domain.Aggregates.OrderAggregate.TrainSnapshot", b =>
                {
                    b.HasOne("OrderService.Domain.Aggregates.OrderAggregate.TripSegmentSnapshot", null)
                        .WithOne("Train")
                        .HasForeignKey("OrderService.Domain.Aggregates.OrderAggregate.TrainSnapshot", "TripSegmentSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("OrderService.Domain.Aggregates.OrderAggregate.TripSegmentSnapshot", b =>
                {
                    b.HasOne("OrderService.Domain.Aggregates.OrderAggregate.TripSnapshot", null)
                        .WithMany("Segments")
                        .HasForeignKey("TripSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("OrderService.Domain.Aggregates.OrderAggregate.TripSnapshot", b =>
                {
                    b.HasOne("OrderService.Domain.Aggregates.OrderAggregate.TicketReservation", null)
                        .WithOne("Trip")
                        .HasForeignKey("OrderService.Domain.Aggregates.OrderAggregate.TripSnapshot", "TicketReservationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("OrderService.Domain.Aggregates.OrderAggregate.Order", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("OrderService.Domain.Aggregates.OrderAggregate.TicketReservation", b =>
                {
                    b.Navigation("Trip")
                        .IsRequired();
                });

            modelBuilder.Entity("OrderService.Domain.Aggregates.OrderAggregate.TripSegmentSnapshot", b =>
                {
                    b.Navigation("Train")
                        .IsRequired();
                });

            modelBuilder.Entity("OrderService.Domain.Aggregates.OrderAggregate.TripSnapshot", b =>
                {
                    b.Navigation("Segments");
                });
#pragma warning restore 612, 618
        }
    }
}
